### ISSUE TITLE
Missing WazuhSvc Service after remote windows agent upgrade via dashboard or console | Wazuh Server 4.9.0

### ISSUE THREAD

**Issue by glosappio** [wazuh/wazuh-agent#153]
Remotely upgrading windows agents via **Dashboard** or via **/var/ossec/bin/agent_upgrade** in same cases would cause the agent to disconnect after upgrade. In those cases I noticed the Wazuhsvc service is missing  and trying to start the agent from the client would return the message **Unable to start agent (check config).**
I could solve it by executing on prompt command C:\Program Files (x86)\ossec-agent>wazuh-agent.exe install-service

**Comment by CKatzsch** [comment]
We have the same error. 

The server was originally installed with version 4.8.0 and then updated to version 4.8.1 and finally to 4.9.0. After the update to version 4.8.1, the problem occurred that the EXE file for the service disappeared after the remote update. The remaining files are still available.

Get-Service WazuhSvc
Get-Service: Cannot find any service with service name 'WazuhSvc'.

The server is installed using the ova file on VMware esxi for evaluation purposes.

**Comment by MarcelKemp** [comment]
Hi @glosappio and @CKatzsch,

After testing, I have not been able to replicate the problem, and looking to see if there are any known bugs for 4.9.0, this does not seem to be the case:
- https://github.com/wazuh/wazuh/issues/26149

@glosappio could you tell me the **version before** the Windows agent upgrade, and the **version you upgraded to**?

@CKatzsch when you upgraded to `4.9.0` the problem was solved? Or did you still have the same problem?

The only known problem affecting `4.7.X` and `4.8.X` versions, is the following:
- https://github.com/wazuh/wazuh/issues/24078

However, it is already fixed for `4.9.0`. Can you confirm if this is your case? And if not, can you give me a bit more context?

**Comment by CKatzsch** [comment]
Hi @MarcelKemp 

Unfortunately the Problem was not Not solved after upgrading to 4.9.0. 

What I've figured out is that it's, in my Case, propably not a remote update problem. Yesterday I've updated the Agent through the uninstalling v4.8.0 and installing v4.9.0. Today or maybe already yesterday the exe file for the service was missing again.

The os ist Windows 10 Enterprise 22H2.

**Comment by glosappio** [comment]
@MarcelKemp the upgrade path was from 4.8.0 to 4.9.0
Once the upgrade command is sent to to the client via Dashboard or manager CLI, the agent appears disconnected. RDP to the client and browsing to **C:\Program Files (x86)\ossec-agent** is brohibited unless you get folder ownership. It happend on several Windows clients (Windows 10, Windows Server 2008 R2 Standard, Windows Server 2012 R2 Standard)

**Comment by MarcelKemp** [comment]
Hi again @CKatzsch & @glosappio, 

I have done a couple of tests upgrading the agent in my environment, however, I have not found any problem that would cause the Wazuh service to disappear. In my case, I have done the following:
1. Uninstall the Wazuh agent and delete the _ossec-agent_ folder (to emulate a clean environment).
2. Install the Wazuh `4.8.0` agent, connect it to a manager and start it, verifying that it is running correctly.
3. In the manager, run the remote upgrade, so that it installs the `4.9.0` version, and wait until it has been successfully upgraded `4.8.0` -> `4.9.0`.
4. Once in the agent, open the _ossec_-agent folder from the file explorer (giving the necessary permissions to the user to access it).
5. Verify that everything works correctly:
   - Verify that the `wazuh-agent.exe` file is located in `ossec-agent`.
   - Open the GUI and check that the agent is running correctly.
   - Verify that the agent is still actively connected to the manager.
   - Open the task manager and check that the Wazuh service is still running correctly.

Performing these tests, everything has worked correctly, as expected. 

Potential problems:
- Since `4.9.0`, after upgrading the agent via WPK, all permissions to the _ossec-agent_ folder along with all its files are removed (for a security issue), keeping only the **`SYSTEM`**/**`Administrators`** permission, which allows Wazuh to continue working properly. The rest of the permissions have to be given manually.
> In the case of manual installation, using the MSI, this problem does not occur, as it also adds the `RX` permissions of the user who has installed/upgraded Wazuh using the MSI: 
> - https://github.com/wazuh/wazuh/pull/24175
  - This problem has been fixed in `4.10.0`, in the following PR: https://github.com/wazuh/wazuh/pull/25429

----------------------

In order to detect what your problem is, I need you to provide me with the detailed instructions you are performing, so that I can replicate the problem. 

Also, I would need to know exactly what files you are missing and how you are checking the Wazuh service.
> Please note the permissions issue, because if that's what it is, then it's expected and will be fixed for 4.10.0.

I look forward to your response.

**Comment by MarcelKemp** [comment]
Due to the lack of response and the possibility of being fixed in 4.10.0, I am closing the issue.
If by any chance it happens again, or there is a response to my previous comment, feel free to reopen the issue.

**Comment by CKatzsch** [comment]
@MarcelKemp 
I'm on vacation at the moment. I can test and answer you next week.

**Comment by CKatzsch** [comment]
So, testing done.

I've uninstalled the version 4.8.1 through the msi file, deleted der program folder and installed Version 4.9.0 also with the msi file. Yesterday it worked fine but now the exe file for the agent is missing again.

![grafik](https://github.com/user-attachments/assets/21c6f7b9-33bc-455a-b7a7-888a0b678548)
